// Run: node scripts/seed.mjs
// Make sure you've run supabase/schema.sql in Supabase dashboard first

import { createClient } from '@supabase/supabase-js'
import { readFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))

// Read .env.local
const envPath = join(__dirname, '../.env.local')
const env = {}
try {
  const raw = readFileSync(envPath, 'utf-8')
  for (const line of raw.split('\n')) {
    const [k, ...v] = line.split('=')
    if (k && v.length) env[k.trim()] = v.join('=').trim()
  }
} catch {
  console.error('Could not read .env.local')
  process.exit(1)
}

const supabase = createClient(
  env.NEXT_PUBLIC_SUPABASE_URL,
  env.SUPABASE_SERVICE_ROLE_KEY,
  { auth: { autoRefreshToken: false, persistSession: false } }
)

const products = [
  { slug: 'aloe-vera-gel', name: 'Aloe Vera Gel', category: 'Hair Care', subcategory: 'Featured', price: 800, original_price: null, size: '120ml', description: 'Our pure Aloe Vera Gel is cold-extracted from freshly harvested aloe leaves grown in Pakistan\'s fertile plains. Rich in vitamins, minerals, and natural enzymes, it provides deep hydration, soothes an irritated scalp, and conditions hair from root to tip — leaving strands soft, shiny, and frizz-free.', benefits: ['Deeply hydrates and conditions dry, damaged hair', 'Soothes scalp irritation and reduces dandruff', 'Defines curls and tames frizz naturally'], how_to_use: 'Apply a generous amount to damp or dry hair from roots to ends. Leave in for 20–30 minutes for a deep conditioning treatment, or style as desired. Rinse thoroughly with lukewarm water. Use 2–3 times a week for best results.', ingredients: 'Aloe Barbadensis Leaf Juice (99%), Xanthan Gum (0.5%), Citric Acid (0.3%), Potassium Sorbate (0.2%)', image_url: 'https://placehold.co/600x800/EEF5FA/2A6496?text=Aloe+Vera+Gel', badge: 'Best Seller', stock_quantity: 50, is_active: true, rating: 4.8, review_count: 24, bg_color: '#EEF5FA', text_color: '#2A6496' },
  { slug: 'rosehip-oil', name: 'Rosehip Oil', category: 'Carrier Oils', subcategory: 'Featured', price: 1350, original_price: null, size: '30ml', description: 'Cold-pressed from the seeds of wild Rosa canina roses, our Rosehip Oil is a concentrated elixir rich in essential fatty acids, vitamins A and C, and antioxidants. Lightweight and fast-absorbing, it nourishes hair follicles, promotes growth, and adds a brilliant, natural-looking shine.', benefits: ['Rich in Vitamin A & C to stimulate hair growth', 'Deeply nourishes scalp and strengthens hair follicles', 'Adds brilliant shine and reduces split ends'], how_to_use: 'Warm 3–5 drops between your palms. Apply directly to scalp and massage gently for 5 minutes. Work remaining oil through hair lengths. Leave overnight or for minimum 2 hours before washing. For daily shine, apply 1–2 drops to dry hair ends.', ingredients: 'Rosa Canina Fruit Oil (100%)', image_url: 'https://placehold.co/600x800/F7F4EF/7D9B77?text=Rosehip+Oil', badge: 'Best Seller', stock_quantity: 50, is_active: true, rating: 4.9, review_count: 24, bg_color: '#F7F4EF', text_color: '#7D9B77' },
  { slug: 'egg-oil', name: 'Egg Oil', category: 'Hair Care', subcategory: 'Featured', price: 1000, original_price: null, size: '30ml', description: 'Extracted from pure egg yolks through a slow cold-press process, our Egg Oil is one of nature\'s most potent hair restoratives. It mimics the natural lipids of the scalp, delivering deep repair and intense moisture to every strand. Ideal for chemically-treated, heat-damaged, or thinning hair.', benefits: ['Mimics scalp\'s natural lipids for deep repair', 'Strengthens hair shaft and reduces breakage', 'Promotes new hair growth and thickness'], how_to_use: 'Apply 4–6 drops to scalp and massage in circular motions for 5–10 minutes. Distribute through hair lengths using your fingers. Leave for 1–2 hours or overnight under a shower cap. Wash out with a gentle sulfate-free shampoo.', ingredients: 'Ovum (Egg Yolk) Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Egg+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.7, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'garlic-oil', name: 'Garlic Oil', category: 'Hair Care', subcategory: 'Featured', price: 1000, original_price: null, size: '30ml', description: 'Ancient wisdom meets modern purity. Our Garlic Oil is infused through a cold extraction process preserving allicin — garlic\'s most active compound — known for its powerful antifungal, antibacterial, and circulation-boosting properties.', benefits: ['Allicin fights dandruff-causing fungi and bacteria', 'Boosts scalp circulation to stimulate hair growth', 'Strengthens hair roots and reduces shedding'], how_to_use: 'Apply 3–5 drops directly to the scalp. Massage in circular motions for 10 minutes to boost circulation. Leave on for 30 minutes to 1 hour. Wash out thoroughly. Use once or twice a week.', ingredients: 'Allium Sativum (Garlic) Oil (100%)', image_url: 'https://placehold.co/600x800/EEF5FA/5B9EC9?text=Garlic+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.6, review_count: 24, bg_color: '#EEF5FA', text_color: '#5B9EC9' },
  { slug: 'pumpkin-seed-oil', name: 'Pumpkin Seed Oil', category: 'Essential Oils', subcategory: 'Featured', price: 1200, original_price: null, size: '30ml', description: 'Cold-pressed from the seeds of premium pumpkins, our Pumpkin Seed Oil is rich in zinc, phytosterols, and delta-7-sterine — compounds clinically studied for supporting healthy hair growth.', benefits: ['Rich in zinc and sterols to combat hair thinning', 'Balances scalp oil production for healthier roots', 'Adds volume and density to fine, limp hair'], how_to_use: 'Apply 3–4 drops to the scalp and massage gently. Can be used alone or blended with a carrier oil. Leave on for 30–45 minutes before shampooing.', ingredients: 'Cucurbita Pepo (Pumpkin) Seed Oil (100%)', image_url: 'https://placehold.co/600x800/EEF5FA/2A6496?text=Pumpkin+Seed+Oil', badge: 'New', stock_quantity: 50, is_active: true, rating: 4.5, review_count: 24, bg_color: '#EEF5FA', text_color: '#2A6496' },
  { slug: 'hemp-seed-oil', name: 'Hemp Seed Oil', category: 'Carrier Oils', subcategory: 'Featured', price: 1000, original_price: null, size: '30ml', description: 'Sourced from organically grown hemp seeds, our Hemp Seed Oil has a perfect ratio of Omega-3 to Omega-6 fatty acids (1:3) that closely mirrors what the human body naturally produces.', benefits: ['Perfect Omega 3:6 ratio mirrors skin\'s natural lipids', 'Reduces scalp inflammation and itchiness', 'Lightweight formula absorbs fast without greasiness'], how_to_use: 'Apply 3–5 drops to scalp and distribute through hair. Can be used as a daily leave-in treatment on ends or as a pre-wash mask.', ingredients: 'Cannabis Sativa (Hemp) Seed Oil (100%)', image_url: 'https://placehold.co/600x800/F7F4EF/7D9B77?text=Hemp+Seed+Oil', badge: 'New', stock_quantity: 50, is_active: true, rating: 4.6, review_count: 24, bg_color: '#F7F4EF', text_color: '#7D9B77' },
  { slug: 'turmeric-oil', name: 'Turmeric Oil', category: 'Essential Oils', subcategory: 'Featured', price: 1200, original_price: null, size: '30ml', description: 'Distilled from the finest Pakistani turmeric roots, our Turmeric Oil harnesses curcumin — one of nature\'s most powerful anti-inflammatory and antioxidant compounds.', benefits: ['Curcumin reduces scalp inflammation and dandruff', 'Antioxidants protect hair from environmental damage', 'Adds golden warmth and vitality to dull hair'], how_to_use: 'Mix 2–3 drops with a carrier oil. Apply to scalp and hair. Leave for 20–30 minutes before washing. Note: may temporarily tint blonde or white hair.', ingredients: 'Curcuma Longa (Turmeric) Root Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Turmeric+Oil', badge: 'New', stock_quantity: 50, is_active: true, rating: 4.7, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'vitamin-e-oil', name: 'Vitamin E Oil', category: 'Carrier Oils', subcategory: 'Featured', price: 1500, original_price: null, size: '30ml', description: 'Our pure Vitamin E Oil (tocopherol) is cold-extracted from natural wheat germ and sunflower sources. A potent antioxidant and skin-conditioning agent, it protects hair from free radical damage.', benefits: ['Potent antioxidant protection against free radicals', 'Seals hair cuticle to lock in moisture and shine', 'Supports scalp health and accelerates hair growth'], how_to_use: 'Use 2–4 drops mixed with your favourite carrier oil for a nourishing hair mask. Apply to scalp and lengths, leave for 30 minutes to 2 hours, then shampoo out.', ingredients: 'Tocopherol (Vitamin E) (100% Natural Source)', image_url: 'https://placehold.co/600x800/EEF5FA/5B9EC9?text=Vitamin+E+Oil', badge: 'New', stock_quantity: 50, is_active: true, rating: 4.8, review_count: 24, bg_color: '#EEF5FA', text_color: '#5B9EC9' },
  { slug: 'aloe-vera-oil', name: 'Aloe Vera Oil', category: 'Hair Care', subcategory: 'Featured', price: 1000, original_price: null, size: '30ml', description: 'A lightweight oil infused with the goodness of aloe vera, ideal for daily scalp nourishment and frizz control.', benefits: ['Soothes and hydrates the scalp', 'Controls frizz and adds shine', 'Suitable for daily use'], how_to_use: 'Apply a few drops to the scalp and hair. Massage gently. Leave in or rinse after 30 minutes.', ingredients: 'Aloe Barbadensis Leaf Oil (100%)', image_url: 'https://placehold.co/600x800/EEF5FA/2A6496?text=Aloe+Vera+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.6, review_count: 24, bg_color: '#EEF5FA', text_color: '#2A6496' },
  { slug: 'carrot-seed-oil', name: 'Carrot Seed Oil', category: 'Essential Oils', subcategory: 'Featured', price: 1350, original_price: null, size: '30ml', description: 'Rich in beta-carotene and vitamins, Carrot Seed Oil deeply nourishes hair and promotes a healthy scalp environment.', benefits: ['Rich in beta-carotene for hair vitality', 'Promotes scalp circulation', 'Protects hair from UV damage'], how_to_use: 'Mix 2–3 drops with a carrier oil. Apply to scalp and hair. Leave for 30 minutes then rinse.', ingredients: 'Daucus Carota (Carrot) Seed Oil (100%)', image_url: 'https://placehold.co/600x800/EEF5FA/2A6496?text=Carrot+Seed+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.5, review_count: 24, bg_color: '#EEF5FA', text_color: '#2A6496' },
  { slug: 'radish-oil', name: 'Radish Oil', category: 'Hair Care', subcategory: 'Featured', price: 1000, original_price: null, size: '30ml', description: 'Cold-pressed radish oil is a traditional hair care staple known for strengthening hair roots and reducing hair fall.', benefits: ['Strengthens hair roots', 'Reduces hair fall', 'Adds natural luster'], how_to_use: 'Massage into scalp 1–2 times a week. Leave for 1 hour then wash out.', ingredients: 'Raphanus Sativus (Radish) Seed Oil (100%)', image_url: 'https://placehold.co/600x800/EEF5FA/2A6496?text=Radish+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.4, review_count: 24, bg_color: '#EEF5FA', text_color: '#2A6496' },
  { slug: 'argan-oil', name: 'Argan Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 2000, original_price: null, size: '30ml', description: 'Known as "liquid gold", our pure Argan Oil is cold-pressed from Moroccan argan kernels. Rich in Vitamin E and fatty acids, it repairs damaged hair and adds brilliant shine.', benefits: ['Repairs split ends and damage', 'Adds frizz-free shine', 'Lightweight and fast-absorbing'], how_to_use: 'Apply 3–5 drops to damp or dry hair. Focus on mid-lengths to ends. Style as usual.', ingredients: 'Argania Spinosa Kernel Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Argan+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.9, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'avocado-oil', name: 'Avocado Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1350, original_price: null, size: '30ml', description: 'Pressed from ripe avocados, this nutrient-dense oil penetrates deep into the hair shaft to restore moisture and elasticity.', benefits: ['Deep moisture restoration', 'Improves hair elasticity', 'Rich in vitamins A, D & E'], how_to_use: 'Apply to scalp and hair. Leave for 30–60 minutes. Rinse thoroughly.', ingredients: 'Persea Gratissima (Avocado) Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Avocado+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.7, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'bergamot-oil', name: 'Bergamot Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1500, original_price: null, size: '30ml', description: 'Steam-distilled from the peel of bergamot citrus, this oil adds a fresh, uplifting scent while promoting scalp health and hair shine.', benefits: ['Promotes scalp health', 'Fresh citrus fragrance', 'Balances scalp oil production'], how_to_use: 'Dilute 3–5 drops with a carrier oil before applying to scalp. Do not use undiluted.', ingredients: 'Citrus Bergamia (Bergamot) Peel Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Bergamot+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.5, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'cedarwood-oil', name: 'Cedarwood Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1500, original_price: null, size: '30ml', description: 'Steam-distilled from cedar bark, Cedarwood Oil has proven antifungal properties and stimulates the scalp to promote hair growth.', benefits: ['Stimulates hair follicles', 'Antifungal — fights dandruff', 'Warm, woody aroma'], how_to_use: 'Mix 5 drops with 2 tbsp of a carrier oil. Massage into scalp. Leave 30 minutes. Rinse.', ingredients: 'Cedrus Atlantica Bark Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Cedarwood+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.6, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'cinnamon-oil', name: 'Cinnamon Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1350, original_price: null, size: '30ml', description: 'Distilled from pure cinnamon bark, this warming oil boosts scalp circulation and has natural antimicrobial properties.', benefits: ['Boosts scalp blood circulation', 'Antimicrobial protection', 'Warming, spicy aroma'], how_to_use: 'Always dilute — 2 drops per tablespoon of carrier oil. Patch test first. Massage into scalp.', ingredients: 'Cinnamomum Zeylanicum Bark Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Cinnamon+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.4, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'clove-oil', name: 'Clove Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1350, original_price: null, size: '30ml', description: 'Extracted from clove buds, this powerful oil is rich in eugenol — a natural antiseptic that fights scalp infections and stimulates growth.', benefits: ['Eugenol fights scalp infections', 'Stimulates dormant follicles', 'Strong antiseptic properties'], how_to_use: 'Dilute heavily — 1–2 drops per tablespoon of carrier oil. Patch test required. Leave 20 min.', ingredients: 'Syzygium Aromaticum (Clove) Bud Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Clove+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.3, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'eucalyptus-oil', name: 'Eucalyptus Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1350, original_price: null, size: '30ml', description: 'Steam-distilled eucalyptus oil cools and refreshes the scalp while fighting dandruff-causing microbes and promoting healthy hair growth.', benefits: ['Cooling, refreshing scalp sensation', 'Fights dandruff and microbes', 'Promotes healthy hair growth'], how_to_use: 'Dilute 5 drops in 2 tbsp carrier oil. Massage into scalp. Leave 30 min. Rinse well.', ingredients: 'Eucalyptus Globulus Leaf Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Eucalyptus+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.6, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'frankincense-oil', name: 'Frankincense Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1500, original_price: null, size: '30ml', description: 'Revered for centuries, Frankincense Oil rejuvenates hair follicles, reduces scalp inflammation, and adds a deep, resinous fragrance.', benefits: ['Rejuvenates hair follicles', 'Reduces scalp inflammation', 'Deep, grounding aroma'], how_to_use: 'Mix 4–5 drops with a carrier oil. Apply to scalp and hair. Leave 30–60 minutes.', ingredients: 'Boswellia Carterii Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Frankincense+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.7, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'grapeseed-oil', name: 'Grapeseed Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1500, original_price: null, size: '30ml', description: 'Cold-pressed from grape seeds, this ultra-lightweight oil is rich in linoleic acid and antioxidants — perfect for fine hair that needs moisture without weight.', benefits: ['Ultra-lightweight, non-greasy', 'Rich in linoleic acid', 'Strengthens hair and adds shine'], how_to_use: 'Apply 3–5 drops to damp or dry hair. Can be used daily as a leave-in serum.', ingredients: 'Vitis Vinifera (Grape) Seed Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Grapeseed+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.6, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'jojoba-oil', name: 'Jojoba Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1350, original_price: null, size: '30ml', description: 'Technically a liquid wax, Jojoba Oil mimics the scalp\'s natural sebum more closely than any other oil — making it exceptional for balancing oil production.', benefits: ['Mimics natural scalp sebum', 'Balances oily and dry scalps', 'Penetrates deep into follicles'], how_to_use: 'Apply 5–8 drops to scalp. Massage for 5 minutes. Can be left in or rinsed after 30 min.', ingredients: 'Simmondsia Chinensis (Jojoba) Seed Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Jojoba+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.8, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'lavender-oil', name: 'Lavender Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1500, original_price: null, size: '30ml', description: 'Steam-distilled from fresh lavender flowers, this classic oil is clinically shown to promote hair growth while delivering a calming, floral fragrance.', benefits: ['Clinically shown to promote growth', 'Calming floral fragrance', 'Reduces scalp inflammation'], how_to_use: 'Mix 5–6 drops with 2 tbsp carrier oil. Apply to scalp nightly or as a weekly treatment.', ingredients: 'Lavandula Angustifolia Flower Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Lavender+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.9, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'lemon-oil', name: 'Lemon Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1350, original_price: null, size: '30ml', description: 'Cold-pressed from lemon peel, this bright, citrus oil clarifies the scalp, removes buildup, and adds a fresh, clean scent to hair.', benefits: ['Clarifies scalp and removes buildup', 'Brightening citrus scent', 'Antiseptic properties'], how_to_use: 'Dilute 3–4 drops in carrier oil. Apply to scalp only. Rinse after 20 minutes. Avoid sun exposure.', ingredients: 'Citrus Limon (Lemon) Peel Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Lemon+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.5, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'lemongrass-oil', name: 'Lemongrass Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1500, original_price: null, size: '30ml', description: 'Steam-distilled from fresh lemongrass, this oil is known for its ability to strengthen hair follicles and control dandruff effectively.', benefits: ['Strengthens hair follicles', 'Controls dandruff', 'Fresh, citrusy aroma'], how_to_use: 'Add 5–6 drops to shampoo or dilute in carrier oil. Massage into scalp. Rinse thoroughly.', ingredients: 'Cymbopogon Citratus Leaf Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Lemongrass+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.6, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'lime-oil', name: 'Lime Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1500, original_price: null, size: '30ml', description: 'Cold-pressed from lime peel, this zesty oil purifies the scalp, controls excess sebum, and gives hair a fresh, clean feel.', benefits: ['Purifies and cleanses the scalp', 'Controls excess oil', 'Zesty, uplifting fragrance'], how_to_use: 'Dilute in carrier oil before applying. Rinse after 20 min. Avoid sun exposure after use.', ingredients: 'Citrus Aurantifolia (Lime) Peel Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Lime+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.4, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'neroli-oil', name: 'Neroli Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1500, original_price: null, size: '30ml', description: 'Distilled from bitter orange blossoms, Neroli Oil is a luxurious, calming oil that nourishes fine hair and promotes a healthy, moisturised scalp.', benefits: ['Nourishes fine and delicate hair', 'Calming floral-citrus aroma', 'Hydrates and balances scalp'], how_to_use: 'Mix 3–4 drops in a carrier oil. Apply to scalp and lengths. Leave 30 min then rinse.', ingredients: 'Citrus Aurantium Amara Flower Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Neroli+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.7, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'orange-oil', name: 'Orange Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1500, original_price: null, size: '30ml', description: 'Cold-pressed from sweet orange peel, this cheerful oil adds shine, fights dandruff, and fills hair with a warm, sweet citrus fragrance.', benefits: ['Adds shine and softness', 'Fights dandruff naturally', 'Sweet, uplifting citrus aroma'], how_to_use: 'Dilute 4–5 drops in carrier oil. Apply to scalp, leave 30 min. Rinse. Avoid sun exposure.', ingredients: 'Citrus Sinensis (Orange) Peel Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Orange+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.5, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'patchouli-oil', name: 'Patchouli Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1500, original_price: null, size: '30ml', description: 'Steam-distilled from patchouli leaves, this deep, earthy oil moisturises the scalp, controls dandruff, and adds a distinctive musky fragrance.', benefits: ['Deeply moisturises scalp', 'Controls dandruff and dryness', 'Rich, musky earthy aroma'], how_to_use: 'Mix 4–5 drops in carrier oil. Apply to scalp. Leave 30–60 min then rinse thoroughly.', ingredients: 'Pogostemon Cablin Leaf Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Patchouli+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.5, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'peppermint-oil', name: 'Peppermint Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1500, original_price: null, size: '30ml', description: 'Steam-distilled peppermint oil provides an invigorating cooling sensation, stimulates scalp blood flow, and is clinically linked to increased hair growth.', benefits: ['Stimulates scalp circulation', 'Clinically linked to hair growth', 'Invigorating cooling sensation'], how_to_use: 'Dilute 3–5 drops in carrier oil. Massage into scalp for 5 min. Leave 20 min then rinse.', ingredients: 'Mentha Piperita (Peppermint) Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Peppermint+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.8, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'rose-oil', name: 'Rose Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1350, original_price: null, size: '30ml', description: 'Distilled from hundreds of fresh rose petals, Rose Oil is one of the most precious hair oils — deeply nourishing, hydrating, and enchantingly fragrant.', benefits: ['Intensely nourishes and hydrates', 'Enchanting floral fragrance', 'Softens and adds shine'], how_to_use: 'Mix 2–3 drops in carrier oil. Apply to hair and scalp. Leave for 30–60 minutes. Rinse.', ingredients: 'Rosa Damascena Flower Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Rose+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.9, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'rosemary-oil', name: 'Rosemary Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1500, original_price: null, size: '30ml', description: 'Clinical studies confirm Rosemary Oil is as effective as minoxidil for promoting hair growth. A must-have for anyone dealing with thinning or shedding hair.', benefits: ['Clinically proven to promote growth', 'Stimulates dormant follicles', 'Strengthens and thickens hair'], how_to_use: 'Apply 5–6 drops to scalp nightly mixed with a carrier oil. Massage in well. No rinsing needed.', ingredients: 'Rosmarinus Officinalis (Rosemary) Leaf Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Rosemary+Oil', badge: 'Best Seller', stock_quantity: 50, is_active: true, rating: 4.9, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'sandalwood-oil', name: 'Sandalwood Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1500, original_price: null, size: '30ml', description: 'Steam-distilled from aged sandalwood, this luxurious oil conditions hair deeply, reduces frizz, and leaves a long-lasting warm, woody fragrance.', benefits: ['Deep conditioning for dry hair', 'Reduces frizz and flyaways', 'Warm, long-lasting woody aroma'], how_to_use: 'Mix 4–5 drops in carrier oil. Apply to hair. Leave 1–2 hours or overnight. Rinse.', ingredients: 'Santalum Album (Sandalwood) Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Sandalwood+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.7, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'tea-tree-oil', name: 'Tea Tree Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1500, original_price: null, size: '30ml', description: 'One of the most researched essential oils, Tea Tree Oil is a powerful antifungal and antibacterial agent — the gold standard treatment for dandruff and scalp conditions.', benefits: ['Eliminates dandruff-causing fungi', 'Antibacterial scalp treatment', 'Unclogs hair follicles'], how_to_use: 'Add 5 drops to shampoo or dilute in carrier oil. Massage into scalp. Leave 5–10 min. Rinse.', ingredients: 'Melaleuca Alternifolia (Tea Tree) Leaf Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Tea+Tree+Oil', badge: 'Best Seller', stock_quantity: 50, is_active: true, rating: 4.8, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'ylang-ylang-oil', name: 'Ylang-Ylang Oil', category: 'Essential Oils', subcategory: 'Essential Oils', price: 1500, original_price: null, size: '30ml', description: 'Steam-distilled from tropical ylang-ylang flowers, this exotic oil balances scalp oil production, reduces breakage, and fills hair with an intoxicating floral fragrance.', benefits: ['Balances sebum production', 'Reduces hair breakage', 'Exotic, floral fragrance'], how_to_use: 'Mix 3–4 drops in carrier oil. Apply to scalp and hair. Leave 30 min. Rinse thoroughly.', ingredients: 'Cananga Odorata Flower Oil (100%)', image_url: 'https://placehold.co/600x800/D4EAF5/1C2B3A?text=Ylang-Ylang+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.6, review_count: 24, bg_color: '#D4EAF5', text_color: '#1C2B3A' },
  { slug: 'sweet-almond-oil', name: 'Sweet Almond Oil', category: 'Carrier Oils', subcategory: 'Carrier Oils', price: 1500, original_price: null, size: '120ml', description: 'Cold-pressed from sweet almonds, this versatile carrier oil is rich in oleic and linoleic acids — perfect for deep conditioning and shine.', benefits: ['Rich in oleic and linoleic acids', 'Deep conditioning carrier', 'Adds brilliant shine'], how_to_use: 'Use alone or as a base for essential oils. Apply to hair and scalp. Leave 30–60 min. Rinse.', ingredients: 'Prunus Amygdalus Dulcis (Sweet Almond) Oil (100%)', image_url: 'https://placehold.co/600x800/F0F7EE/4a6b45?text=Sweet+Almond+Oil', badge: 'Best Seller', stock_quantity: 50, is_active: true, rating: 4.8, review_count: 24, bg_color: '#F0F7EE', text_color: '#4a6b45' },
  { slug: 'bitter-almond-oil', name: 'Bitter Almond Oil', category: 'Carrier Oils', subcategory: 'Carrier Oils', price: 1200, original_price: null, size: '120ml', description: 'Pressed from bitter almond kernels, this nourishing oil strengthens hair and adds a characteristic almond fragrance to blends.', benefits: ['Strengthens hair shaft', 'Adds almond fragrance naturally', 'Nourishes and conditions'], how_to_use: 'Use as a carrier for essential oils. Apply to hair. Leave 1 hour. Rinse thoroughly.', ingredients: 'Prunus Amygdalus Amara (Bitter Almond) Oil (100%)', image_url: 'https://placehold.co/600x800/F0F7EE/4a6b45?text=Bitter+Almond+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.5, review_count: 24, bg_color: '#F0F7EE', text_color: '#4a6b45' },
  { slug: 'coconut-oil', name: 'Coconut Oil', category: 'Carrier Oils', subcategory: 'Carrier Oils', price: 1000, original_price: null, size: '120ml', description: 'Cold-pressed virgin coconut oil is the most researched hair oil in the world — proven to reduce protein loss and penetrate the hair shaft more deeply than any other oil.', benefits: ['Proven to reduce protein loss', 'Deepest penetration of any oil', 'Antimicrobial and moisturising'], how_to_use: 'Warm between palms. Apply generously to hair and scalp. Leave overnight. Rinse in morning.', ingredients: 'Cocos Nucifera (Coconut) Oil (100%)', image_url: 'https://placehold.co/600x800/F0F7EE/4a6b45?text=Coconut+Oil', badge: 'Best Seller', stock_quantity: 50, is_active: true, rating: 4.8, review_count: 24, bg_color: '#F0F7EE', text_color: '#4a6b45' },
  { slug: 'sesame-oil', name: 'Sesame Oil', category: 'Carrier Oils', subcategory: 'Carrier Oils', price: 800, original_price: null, size: '120ml', description: 'A cornerstone of South Asian hair care for generations, sesame oil is deeply nourishing with natural UV protection and scalp-soothing properties.', benefits: ['Natural UV protection', 'Deeply nourishing for dry hair', 'Traditional South Asian remedy'], how_to_use: 'Warm gently and massage into scalp. Leave 1–2 hours or overnight. Rinse with shampoo.', ingredients: 'Sesamum Indicum (Sesame) Seed Oil (100%)', image_url: 'https://placehold.co/600x800/F0F7EE/4a6b45?text=Sesame+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.7, review_count: 24, bg_color: '#F0F7EE', text_color: '#4a6b45' },
  { slug: 'mustard-oil', name: 'Mustard Oil', category: 'Carrier Oils', subcategory: 'Carrier Oils', price: 450, original_price: null, size: '120ml', description: 'Cold-pressed mustard oil is a traditional Pakistani hair care staple known for warming the scalp, stimulating circulation, and promoting thick, lustrous hair.', benefits: ['Warms scalp and boosts circulation', 'Promotes thick, lustrous hair', 'Traditional desi hair remedy'], how_to_use: 'Warm and massage into scalp. Leave for 1–2 hours. Wash out with a mild shampoo.', ingredients: 'Brassica Juncea (Mustard) Seed Oil (100%)', image_url: 'https://placehold.co/600x800/F0F7EE/4a6b45?text=Mustard+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.6, review_count: 24, bg_color: '#F0F7EE', text_color: '#4a6b45' },
  { slug: 'bitter-mustard-oil', name: 'Bitter Mustard Oil', category: 'Carrier Oils', subcategory: 'Carrier Oils', price: 450, original_price: null, size: '120ml', description: 'A stronger variant of mustard oil with a more pungent aroma, known for its potent scalp-stimulating and antimicrobial properties.', benefits: ['Potent scalp stimulation', 'Stronger antimicrobial action', 'Traditional hair growth remedy'], how_to_use: 'Use sparingly. Dilute with a carrier oil if needed. Massage into scalp, leave 1 hr, rinse.', ingredients: 'Brassica Nigra (Bitter Mustard) Seed Oil (100%)', image_url: 'https://placehold.co/600x800/F0F7EE/4a6b45?text=Bitter+Mustard+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.4, review_count: 24, bg_color: '#F0F7EE', text_color: '#4a6b45' },
  { slug: 'olive-oil', name: 'Olive Oil', category: 'Carrier Oils', subcategory: 'Carrier Oils', price: 800, original_price: null, size: '120ml', description: 'Extra virgin olive oil is one of the oldest hair treatments known. Rich in oleic acid and squalene, it deeply moisturises and protects hair from damage.', benefits: ['Rich in oleic acid and squalene', 'Deep moisture and damage protection', 'Time-tested traditional treatment'], how_to_use: 'Warm and apply to hair and scalp. Leave for 1–2 hours or overnight. Rinse with shampoo.', ingredients: 'Olea Europaea (Olive) Fruit Oil (100%)', image_url: 'https://placehold.co/600x800/F0F7EE/4a6b45?text=Olive+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.7, review_count: 24, bg_color: '#F0F7EE', text_color: '#4a6b45' },
  { slug: 'castor-oil', name: 'Castor Oil', category: 'Carrier Oils', subcategory: 'Carrier Oils', price: 600, original_price: null, size: '120ml', description: 'Cold-pressed castor oil is the most popular oil for eyebrow and eyelash growth — and equally effective on the scalp for stimulating thick, dense hair growth.', benefits: ['Stimulates thick, dense growth', 'Rich in ricinoleic acid', 'Popular for brows and lashes'], how_to_use: 'Apply to scalp with a dropper. Massage well. Leave overnight. Rinse in the morning.', ingredients: 'Ricinus Communis (Castor) Seed Oil (100%)', image_url: 'https://placehold.co/600x800/F0F7EE/4a6b45?text=Castor+Oil', badge: 'Best Seller', stock_quantity: 50, is_active: true, rating: 4.8, review_count: 24, bg_color: '#F0F7EE', text_color: '#4a6b45' },
  { slug: 'neem-oil', name: 'Neem Oil', category: 'Carrier Oils', subcategory: 'Carrier Oils', price: 1000, original_price: null, size: '60ml', description: 'Cold-pressed neem oil is a powerful antifungal and insecticidal oil — the ultimate treatment for persistent dandruff, scalp psoriasis, and lice.', benefits: ['Powerful antifungal properties', 'Treats dandruff and psoriasis', 'Natural lice treatment'], how_to_use: 'Mix with a carrier oil (neem is strong). Apply to scalp. Leave 1–2 hours. Rinse thoroughly.', ingredients: 'Azadirachta Indica (Neem) Seed Oil (100%)', image_url: 'https://placehold.co/600x800/F0F7EE/4a6b45?text=Neem+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.6, review_count: 24, bg_color: '#F0F7EE', text_color: '#4a6b45' },
  { slug: 'onion-oil', name: 'Onion Oil', category: 'Carrier Oils', subcategory: 'Carrier Oils', price: 1350, original_price: null, size: '60ml', description: 'Onion Oil is rich in sulphur — the building block of keratin. Clinically studied for reversing hair loss and promoting significant regrowth in as little as 8 weeks.', benefits: ['Rich in sulphur for keratin production', 'Clinically studied for hair regrowth', 'Reduces hair thinning'], how_to_use: 'Apply to scalp with dropper. Massage gently. Leave 30–60 min. Wash out thoroughly.', ingredients: 'Allium Cepa (Onion) Seed Oil (100%)', image_url: 'https://placehold.co/600x800/F0F7EE/4a6b45?text=Onion+Oil', badge: 'Best Seller', stock_quantity: 50, is_active: true, rating: 4.8, review_count: 24, bg_color: '#F0F7EE', text_color: '#4a6b45' },
  { slug: 'kalonji-oil', name: 'Kalonji Oil', category: 'Carrier Oils', subcategory: 'Carrier Oils', price: 1500, original_price: null, size: '120ml', description: 'Black Seed (Kalonji) Oil — mentioned in Islamic tradition as a cure for everything except death. Rich in thymoquinone, it is one of the most potent hair growth oils available.', benefits: ['Thymoquinone supports follicle health', 'Reduces hair loss significantly', 'Antioxidant and anti-inflammatory'], how_to_use: 'Massage into scalp nightly. Leave overnight. Rinse in morning. Use consistently for 3+ months.', ingredients: 'Nigella Sativa (Black Seed) Oil (100%)', image_url: 'https://placehold.co/600x800/F0F7EE/4a6b45?text=Kalonji+Oil', badge: 'Best Seller', stock_quantity: 50, is_active: true, rating: 4.9, review_count: 24, bg_color: '#F0F7EE', text_color: '#4a6b45' },
  { slug: 'flax-seed-oil', name: 'Flax Seed Oil', category: 'Carrier Oils', subcategory: 'Carrier Oils', price: 800, original_price: null, size: '60ml', description: 'Pressed from golden flaxseeds, this omega-3 rich oil strengthens hair from within, reduces breakage, and adds smooth, frizz-free shine.', benefits: ['High in Omega-3 fatty acids', 'Reduces breakage and split ends', 'Smooth, frizz-free finish'], how_to_use: 'Apply to hair and scalp. Leave 30 min. Rinse. Or use 1–2 drops as a daily leave-in serum.', ingredients: 'Linum Usitatissimum (Flaxseed) Seed Oil (100%)', image_url: 'https://placehold.co/600x800/F0F7EE/4a6b45?text=Flax+Seed+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.5, review_count: 24, bg_color: '#F0F7EE', text_color: '#4a6b45' },
  { slug: 'peanut-oil', name: 'Peanut Oil', category: 'Carrier Oils', subcategory: 'Carrier Oils', price: 1200, original_price: null, size: '60ml', description: 'Cold-pressed peanut oil is rich in biotin, vitamin E, and niacin — nutrients essential for hair growth and scalp health.', benefits: ['Rich in biotin for hair growth', 'Vitamin E and niacin for scalp health', 'Deeply nourishing'], how_to_use: 'Warm between palms. Apply to scalp and hair. Leave 30–60 min. Rinse with shampoo.', ingredients: 'Arachis Hypogaea (Peanut) Oil (100%)', image_url: 'https://placehold.co/600x800/F0F7EE/4a6b45?text=Peanut+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.4, review_count: 24, bg_color: '#F0F7EE', text_color: '#4a6b45' },
  { slug: 'amla-oil', name: 'Amla Oil', category: 'Carrier Oils', subcategory: 'Carrier Oils', price: 800, original_price: null, size: '120ml', description: 'Infused with the goodness of Indian gooseberry (amla), this traditional oil is packed with Vitamin C and antioxidants that prevent premature greying and promote thick, dark hair.', benefits: ['Prevents premature greying', 'Rich in Vitamin C antioxidants', 'Promotes thick, dark hair'], how_to_use: 'Warm and massage into scalp. Leave 1–2 hours or overnight. Rinse with mild shampoo.', ingredients: 'Phyllanthus Emblica (Amla) Fruit Oil (100%)', image_url: 'https://placehold.co/600x800/F0F7EE/4a6b45?text=Amla+Oil', badge: null, stock_quantity: 50, is_active: true, rating: 4.7, review_count: 24, bg_color: '#F0F7EE', text_color: '#4a6b45' },
  { slug: 'shea-butter', name: 'Shea Butter', category: 'Butters & Waxes', subcategory: 'Butters', price: 150, original_price: null, size: '50gm', description: 'Unrefined raw shea butter from West African shea trees. Rich in fatty acids and vitamins A, E & F, it is a deeply moisturising butter for hair and skin.', benefits: ['Intensely moisturises and seals', 'Rich in vitamins A, E & F', 'Ideal for dry, coily, or damaged hair'], how_to_use: 'Warm a small amount between palms. Apply to hair ends or use as a scalp sealant. Style as usual.', ingredients: 'Butyrospermum Parkii (Shea) Butter (100%)', image_url: 'https://placehold.co/600x800/F7E8C0/7a4f1a?text=Shea+Butter', badge: null, stock_quantity: 50, is_active: true, rating: 4.7, review_count: 24, bg_color: '#F7E8C0', text_color: '#7a4f1a' },
  { slug: 'cocoa-butter', name: 'Cocoa Butter', category: 'Butters & Waxes', subcategory: 'Butters', price: 150, original_price: null, size: '50gm', description: 'Pure raw cocoa butter with a natural chocolate aroma. It forms a protective barrier over the hair shaft, locking in moisture and adding brilliant shine.', benefits: ['Forms protective moisture barrier', 'Brilliant shine and softness', 'Natural chocolate aroma'], how_to_use: 'Melt a small amount between fingers. Apply to dry ends or use as a pre-wash treatment.', ingredients: 'Theobroma Cacao (Cocoa) Seed Butter (100%)', image_url: 'https://placehold.co/600x800/F7E8C0/7a4f1a?text=Cocoa+Butter', badge: null, stock_quantity: 50, is_active: true, rating: 4.6, review_count: 24, bg_color: '#F7E8C0', text_color: '#7a4f1a' },
  { slug: 'beeswax', name: 'Beeswax', category: 'Butters & Waxes', subcategory: 'Butters', price: 150, original_price: null, size: '50gm', description: 'Pure natural beeswax for sealing and styling hair. It locks in moisture, provides hold without stiffness, and adds a natural protective coating to each strand.', benefits: ['Seals in moisture naturally', 'Provides flexible hold for styling', 'Protective coating for each strand'], how_to_use: 'Soften between fingers and apply sparingly to ends or use for styling and edge control.', ingredients: 'Cera Alba (Beeswax) (100%)', image_url: 'https://placehold.co/600x800/F7E8C0/7a4f1a?text=Beeswax', badge: null, stock_quantity: 50, is_active: true, rating: 4.5, review_count: 24, bg_color: '#F7E8C0', text_color: '#7a4f1a' },
]

async function seed() {
  console.log(`Seeding ${products.length} products into Supabase...`)

  // Upsert all products (insert or update on slug conflict)
  const { data, error } = await supabase
    .from('products')
    .upsert(products, { onConflict: 'slug' })
    .select('id, slug, name')

  if (error) {
    console.error('Seed error:', error.message)
    console.error('Details:', error.details)
    process.exit(1)
  }

  console.log(`\nSuccessfully seeded ${data.length} products:`)
  data.forEach(p => console.log(`  [${p.id}] ${p.slug} — ${p.name}`))

  // Verify count
  const { count } = await supabase
    .from('products')
    .select('*', { count: 'exact', head: true })

  console.log(`\nTotal products in Supabase: ${count}`)
  console.log('\nSeed complete!')
}

seed()
